version: "3.4"

services:
  web:
    build: .
    volumes:
      - .:/var/www
      - ./docker-entry.sh:/etc/entrypoint.sh
    entrypoint: [ "sh", "/etc/entrypoint.sh" ]
    ports:
      - "3310:3310"
    environment:
      PORT: 3310
      DB_HOST: mysql-8vdb.railway.internal
      DB_PORT: 3306
      DB_USER: raphael
      DB_PASSWORD: raphael974
      DB_NAME: DB_NAME
      VITE_API_URL: ""
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:9
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uuser", "-ppassword" ] # Command to check health.
      interval: 5s # Interval between health checks.
      timeout: 5s # Timeout for each health checking.
      retries: 20 # Hou many times retries.
      start_period: 10s
    volumes:
      - ./database-setup.sh:/docker-entrypoint-initdb.d/setup.sh
    #      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: raphael
      MYSQL_PASSWORD: raphael974
      # Password for root access
      MYSQL_ROOT_PASSWORD: raphael974
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
